package com.myspace.datavalidation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Entity implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Name")
    private java.lang.String name;

    @org.kie.api.definition.type.Label(value = "LastName")
    private java.lang.String lastName;

    @org.kie.api.definition.type.Label(value = "Abn")
    private java.lang.String abn;

    public Entity() {
    }

public java.lang.String getAbn() {
		return this.abn;
	}

	public void setAbn(java.lang.String abn) {
		this.abn = abn;
	}

        public java.lang.String getLastName() {
		return this.lastName;
	}

	public void setLastName(java.lang.String lastName) {
		this.lastName = lastName;
	}
        public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Entity(java.lang.String name, java.lang.String abn, java.lang.String lastName) {
		this.name = name;
		this.abn = abn;
		this.lastName = lastName;
	}



}
